# fmt:off
class UserNotLoggedIn(Exception): ...
class UserAlreadyExistsError(Exception): ...
class UserAuthFailed(Exception): ...
class UserNotVerifiedError(Exception): ...
class TokenNotFound(Exception): ...
# fmt:on
