"""Add UserToSlackToken.team_name

Revision ID: 1726779728
Revises: 1726599316
Create Date: 2024-09-19 21:02:08.765439

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1726779728"
down_revision: Union[str, None] = "1726599316"
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_to_slack_token", sa.Column("team_name", sa.String(length=255), nullable=True))

    # All existing tokens are for TeamWeb
    op.execute(sa.text("UPDATE user_to_slack_token SET team_name = 'TeamWeb'"))

    with op.batch_alter_table("user_to_slack_token", schema=None) as batch_op:
        batch_op.alter_column("team_name", existing_type=sa.String(255), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_to_slack_token", "team_name")
    # ### end Alembic commands ###
