"""Add whats_new

Revision ID: 382a30f9ca44
Revises: 9336c8d849a5
Create Date: 2023-07-01 16:46:39.677215

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "382a30f9ca44"
down_revision = "9336c8d849a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whats_new",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_whats_new")),
    )

    with op.batch_alter_table("break", schema=None) as batch_op:
        batch_op.alter_column("time_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("start", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_seen_whats_new", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_user_last_seen_whats_new_whats_new"), "whats_new", ["last_seen_whats_new"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_user_last_seen_whats_new_whats_new"), type_="foreignkey")
        batch_op.drop_column("last_seen_whats_new")

    with op.batch_alter_table("leave", schema=None) as batch_op:
        batch_op.alter_column("public_holiday", existing_type=sa.BOOLEAN(), nullable=True)

    with op.batch_alter_table("break", schema=None) as batch_op:
        batch_op.alter_column("start", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("time_id", existing_type=sa.INTEGER(), nullable=True)

    op.drop_table("whats_new")
    # ### end Alembic commands ###
