"""Add leave.public_holiday

Revision ID: 9336c8d849a5
Revises: f9876948cb9d
Create Date: 2023-05-14 12:40:24.335683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9336c8d849a5"
down_revision = "f9876948cb9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leave", schema=None) as batch_op:
        batch_op.add_column(sa.Column("public_holiday", sa.Boolean(), nullable=True, default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leave", schema=None) as batch_op:
        batch_op.drop_column("public_holiday")

    # ### end Alembic commands ###
