"""Add Leave.user_id

Revision ID: f9876948cb9d
Revises: 90a5d48d48b3
Create Date: 2022-11-21 20:36:56.911154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9876948cb9d'
down_revision = '90a5d48d48b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_leave_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('login_session', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uc_login_session_key'), ['key'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uc_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uc_user_email'), type_='unique')

    with op.batch_alter_table('login_session', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uc_login_session_key'), type_='unique')

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_leave_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
