"""Add UserToSlackToken table

Revision ID: e2d94f8531ec
Revises: 527aba039d23
Create Date: 2024-09-14 18:29:43.392419

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e2d94f8531ec"
down_revision = "527aba039d23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_to_slack_token",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("slack_token", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_user_to_slack_token_user_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_to_slack_token")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_to_slack_token")
    # ### end Alembic commands ###
